---
galaxy_info:
  role_name: phpfpm
  namespace: zz
  description: Install phpfpm
  author: Florian Lohoff <f@zz.de>
  license: CC0
  min_ansible_version: "2.14"
  platforms:
    - name: Debian
      versions:
        - bookworm
        - trixie
